# Generated by Django 5.0.2 on 2024-02-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_firma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name_plural': 'Firma'},
        ),
        migrations.AddField(
            model_name='firma',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Firma Email'),
        ),
        migrations.AddField(
            model_name='firma',
            name='Postleitzahl',
            field=models.CharField(blank=True, max_length=8, verbose_name='Postleitzahl'),
        ),
        migrations.AddField(
            model_name='firma',
            name='Stadt',
            field=models.CharField(blank=True, max_length=30, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='firma',
            name='Strasse',
            field=models.CharField(blank=True, max_length=30, verbose_name='Strasse'),
        ),
        migrations.AddField(
            model_name='firma',
            name='Telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon Firma'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Firma'),
        ),
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nachname', models.CharField(blank=True, max_length=50, verbose_name='Nachname')),
                ('Vorname', models.CharField(blank=True, max_length=50, verbose_name='Vorname')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email Ansprechpartner')),
                ('Telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon Ansprechpartner')),
                ('Firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.firma', verbose_name='Firma')),
            ],
            options={
                'verbose_name_plural': 'Ansprechpartner',
            },
        ),
    ]
