# Generated by Django 5.0.2 on 2024-02-18 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_geruestbuch_eingangsdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geruestbuch',
            name='Eingangsdatum',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 15, 11, 825787, tzinfo=datetime.timezone.utc), verbose_name='Eingangsdatum'),
        ),
    ]
