# Generated by Django 5.0.2 on 2024-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_logmessage_source_alter_logmessage_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
