# Generated by Django 5.0.2 on 2024-02-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_alter_geruestbuch_geruestnummer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geruestbuch',
            name='Grund',
            field=models.TextField(blank=True, help_text='Kurze Begründung warum das Gerüst angefordert wird.', verbose_name='Grund'),
        ),
    ]
